// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ActorHarborProtocol.proto

package com.gg.core.actor.harbor.protocol;

public final class ActorHarborProtocol {
  private ActorHarborProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Handshake = 0;</code>
     *
     * <pre>
     * handshake
     * </pre>
     */
    Handshake(0, 0),
    /**
     * <code>Post = 1;</code>
     *
     * <pre>
     * post
     * </pre>
     */
    Post(1, 1),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>Handshake = 0;</code>
     *
     * <pre>
     * handshake
     * </pre>
     */
    public static final int Handshake_VALUE = 0;
    /**
     * <code>Post = 1;</code>
     *
     * <pre>
     * post
     * </pre>
     */
    public static final int Post_VALUE = 1;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static MessageType valueOf(int value) {
      switch (value) {
        case 0: return Handshake;
        case 1: return Post;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageType)
  }

  public interface ServiceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Service)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * service name
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * service name
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string host = 2;</code>
     *
     * <pre>
     * host addr
     * </pre>
     */
    java.lang.String getHost();
    /**
     * <code>optional string host = 2;</code>
     *
     * <pre>
     * host addr
     * </pre>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>optional int32 port = 3;</code>
     *
     * <pre>
     * port
     * </pre>
     */
    int getPort();
  }
  /**
   * Protobuf type {@code Service}
   */
  public  static final class Service extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Service)
      ServiceOrBuilder {
    // Use Service.newBuilder() to construct.
    private Service(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Service() {
      name_ = "";
      host_ = "";
      port_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Service(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 24: {

              port_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_Service_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_Service_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.class, com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * service name
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * service name
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOST_FIELD_NUMBER = 2;
    private volatile java.lang.Object host_;
    /**
     * <code>optional string host = 2;</code>
     *
     * <pre>
     * host addr
     * </pre>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>optional string host = 2;</code>
     *
     * <pre>
     * host addr
     * </pre>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <code>optional int32 port = 3;</code>
     *
     * <pre>
     * port
     * </pre>
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, host_);
      }
      if (port_ != 0) {
        output.writeInt32(3, port_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Service}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Service)
        com.gg.core.actor.harbor.protocol.ActorHarborProtocol.ServiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_Service_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_Service_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.class, com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.Builder.class);
      }

      // Construct using com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        host_ = "";

        port_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_Service_descriptor;
      }

      public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service getDefaultInstanceForType() {
        return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.getDefaultInstance();
      }

      public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service build() {
        com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service buildPartial() {
        com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service result = new com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service(this);
        result.name_ = name_;
        result.host_ = host_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service) {
          return mergeFrom((com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service other) {
        if (other == com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * service name
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * service name
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * service name
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * service name
       * </pre>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * service name
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>optional string host = 2;</code>
       *
       * <pre>
       * host addr
       * </pre>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string host = 2;</code>
       *
       * <pre>
       * host addr
       * </pre>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string host = 2;</code>
       *
       * <pre>
       * host addr
       * </pre>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string host = 2;</code>
       *
       * <pre>
       * host addr
       * </pre>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string host = 2;</code>
       *
       * <pre>
       * host addr
       * </pre>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>optional int32 port = 3;</code>
       *
       * <pre>
       * port
       * </pre>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>optional int32 port = 3;</code>
       *
       * <pre>
       * port
       * </pre>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 port = 3;</code>
       *
       * <pre>
       * port
       * </pre>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Service)
    }

    // @@protoc_insertion_point(class_scope:Service)
    private static final com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service();
    }

    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Service>
        PARSER = new com.google.protobuf.AbstractParser<Service>() {
      public Service parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Service(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Service> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Service> getParserForType() {
      return PARSER;
    }

    public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HandshakeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HandshakeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Service source = 1;</code>
     */
    boolean hasSource();
    /**
     * <code>optional .Service source = 1;</code>
     */
    com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service getSource();
    /**
     * <code>optional .Service source = 1;</code>
     */
    com.gg.core.actor.harbor.protocol.ActorHarborProtocol.ServiceOrBuilder getSourceOrBuilder();
  }
  /**
   * Protobuf type {@code HandshakeMessage}
   */
  public  static final class HandshakeMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HandshakeMessage)
      HandshakeMessageOrBuilder {
    // Use HandshakeMessage.newBuilder() to construct.
    private HandshakeMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HandshakeMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HandshakeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.Builder subBuilder = null;
              if (source_ != null) {
                subBuilder = source_.toBuilder();
              }
              source_ = input.readMessage(com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(source_);
                source_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_HandshakeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_HandshakeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage.class, com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage.Builder.class);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    private com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service source_;
    /**
     * <code>optional .Service source = 1;</code>
     */
    public boolean hasSource() {
      return source_ != null;
    }
    /**
     * <code>optional .Service source = 1;</code>
     */
    public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service getSource() {
      return source_ == null ? com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.getDefaultInstance() : source_;
    }
    /**
     * <code>optional .Service source = 1;</code>
     */
    public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.ServiceOrBuilder getSourceOrBuilder() {
      return getSource();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (source_ != null) {
        output.writeMessage(1, getSource());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (source_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSource());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HandshakeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HandshakeMessage)
        com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_HandshakeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_HandshakeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage.class, com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage.Builder.class);
      }

      // Construct using com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (sourceBuilder_ == null) {
          source_ = null;
        } else {
          source_ = null;
          sourceBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_HandshakeMessage_descriptor;
      }

      public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage getDefaultInstanceForType() {
        return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage.getDefaultInstance();
      }

      public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage build() {
        com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage buildPartial() {
        com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage result = new com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage(this);
        if (sourceBuilder_ == null) {
          result.source_ = source_;
        } else {
          result.source_ = sourceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage) {
          return mergeFrom((com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage other) {
        if (other == com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage.getDefaultInstance()) return this;
        if (other.hasSource()) {
          mergeSource(other.getSource());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service source_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service, com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.Builder, com.gg.core.actor.harbor.protocol.ActorHarborProtocol.ServiceOrBuilder> sourceBuilder_;
      /**
       * <code>optional .Service source = 1;</code>
       */
      public boolean hasSource() {
        return sourceBuilder_ != null || source_ != null;
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service getSource() {
        if (sourceBuilder_ == null) {
          return source_ == null ? com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.getDefaultInstance() : source_;
        } else {
          return sourceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public Builder setSource(com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service value) {
        if (sourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          source_ = value;
          onChanged();
        } else {
          sourceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public Builder setSource(
          com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.Builder builderForValue) {
        if (sourceBuilder_ == null) {
          source_ = builderForValue.build();
          onChanged();
        } else {
          sourceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public Builder mergeSource(com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service value) {
        if (sourceBuilder_ == null) {
          if (source_ != null) {
            source_ =
              com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.newBuilder(source_).mergeFrom(value).buildPartial();
          } else {
            source_ = value;
          }
          onChanged();
        } else {
          sourceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public Builder clearSource() {
        if (sourceBuilder_ == null) {
          source_ = null;
          onChanged();
        } else {
          source_ = null;
          sourceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.Builder getSourceBuilder() {
        
        onChanged();
        return getSourceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.ServiceOrBuilder getSourceOrBuilder() {
        if (sourceBuilder_ != null) {
          return sourceBuilder_.getMessageOrBuilder();
        } else {
          return source_ == null ?
              com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.getDefaultInstance() : source_;
        }
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service, com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.Builder, com.gg.core.actor.harbor.protocol.ActorHarborProtocol.ServiceOrBuilder> 
          getSourceFieldBuilder() {
        if (sourceBuilder_ == null) {
          sourceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service, com.gg.core.actor.harbor.protocol.ActorHarborProtocol.Service.Builder, com.gg.core.actor.harbor.protocol.ActorHarborProtocol.ServiceOrBuilder>(
                  getSource(),
                  getParentForChildren(),
                  isClean());
          source_ = null;
        }
        return sourceBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:HandshakeMessage)
    }

    // @@protoc_insertion_point(class_scope:HandshakeMessage)
    private static final com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage();
    }

    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HandshakeMessage>
        PARSER = new com.google.protobuf.AbstractParser<HandshakeMessage>() {
      public HandshakeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new HandshakeMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<HandshakeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HandshakeMessage> getParserForType() {
      return PARSER;
    }

    public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.HandshakeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RemoteActorMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RemoteActorMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .MessageType type = 1;</code>
     *
     * <pre>
     * msg type
     * </pre>
     */
    int getTypeValue();
    /**
     * <code>optional .MessageType type = 1;</code>
     *
     * <pre>
     * msg type
     * </pre>
     */
    com.gg.core.actor.harbor.protocol.ActorHarborProtocol.MessageType getType();

    /**
     * <code>optional bytes payload = 2;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code RemoteActorMessage}
   */
  public  static final class RemoteActorMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RemoteActorMessage)
      RemoteActorMessageOrBuilder {
    // Use RemoteActorMessage.newBuilder() to construct.
    private RemoteActorMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RemoteActorMessage() {
      type_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RemoteActorMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {

              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_RemoteActorMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_RemoteActorMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage.class, com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .MessageType type = 1;</code>
     *
     * <pre>
     * msg type
     * </pre>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .MessageType type = 1;</code>
     *
     * <pre>
     * msg type
     * </pre>
     */
    public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.MessageType getType() {
      com.gg.core.actor.harbor.protocol.ActorHarborProtocol.MessageType result = com.gg.core.actor.harbor.protocol.ActorHarborProtocol.MessageType.valueOf(type_);
      return result == null ? com.gg.core.actor.harbor.protocol.ActorHarborProtocol.MessageType.UNRECOGNIZED : result;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>optional bytes payload = 2;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.gg.core.actor.harbor.protocol.ActorHarborProtocol.MessageType.Handshake.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(2, payload_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.gg.core.actor.harbor.protocol.ActorHarborProtocol.MessageType.Handshake.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RemoteActorMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RemoteActorMessage)
        com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_RemoteActorMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_RemoteActorMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage.class, com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage.Builder.class);
      }

      // Construct using com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.internal_static_RemoteActorMessage_descriptor;
      }

      public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage getDefaultInstanceForType() {
        return com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage.getDefaultInstance();
      }

      public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage build() {
        com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage buildPartial() {
        com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage result = new com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage(this);
        result.type_ = type_;
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage) {
          return mergeFrom((com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage other) {
        if (other == com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .MessageType type = 1;</code>
       *
       * <pre>
       * msg type
       * </pre>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .MessageType type = 1;</code>
       *
       * <pre>
       * msg type
       * </pre>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .MessageType type = 1;</code>
       *
       * <pre>
       * msg type
       * </pre>
       */
      public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.MessageType getType() {
        com.gg.core.actor.harbor.protocol.ActorHarborProtocol.MessageType result = com.gg.core.actor.harbor.protocol.ActorHarborProtocol.MessageType.valueOf(type_);
        return result == null ? com.gg.core.actor.harbor.protocol.ActorHarborProtocol.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .MessageType type = 1;</code>
       *
       * <pre>
       * msg type
       * </pre>
       */
      public Builder setType(com.gg.core.actor.harbor.protocol.ActorHarborProtocol.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .MessageType type = 1;</code>
       *
       * <pre>
       * msg type
       * </pre>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes payload = 2;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>optional bytes payload = 2;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes payload = 2;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RemoteActorMessage)
    }

    // @@protoc_insertion_point(class_scope:RemoteActorMessage)
    private static final com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage();
    }

    public static com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RemoteActorMessage>
        PARSER = new com.google.protobuf.AbstractParser<RemoteActorMessage>() {
      public RemoteActorMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new RemoteActorMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<RemoteActorMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RemoteActorMessage> getParserForType() {
      return PARSER;
    }

    public com.gg.core.actor.harbor.protocol.ActorHarborProtocol.RemoteActorMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Service_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Service_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HandshakeMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HandshakeMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoteActorMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RemoteActorMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ActorHarborProtocol.proto\"3\n\007Service\022\014" +
      "\n\004name\030\001 \001(\t\022\014\n\004host\030\002 \001(\t\022\014\n\004port\030\003 \001(\005" +
      "\",\n\020HandshakeMessage\022\030\n\006source\030\001 \001(\0132\010.S" +
      "ervice\"A\n\022RemoteActorMessage\022\032\n\004type\030\001 \001" +
      "(\0162\014.MessageType\022\017\n\007payload\030\002 \001(\014*&\n\013Mes" +
      "sageType\022\r\n\tHandshake\020\000\022\010\n\004Post\020\0012D\n\014IAc" +
      "torHarbor\0224\n\004post\022\023.RemoteActorMessage\032\023" +
      ".RemoteActorMessage(\0010\001B#\n!com.gg.core.a" +
      "ctor.harbor.protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Service_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Service_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Service_descriptor,
        new java.lang.String[] { "Name", "Host", "Port", });
    internal_static_HandshakeMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HandshakeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HandshakeMessage_descriptor,
        new java.lang.String[] { "Source", });
    internal_static_RemoteActorMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RemoteActorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RemoteActorMessage_descriptor,
        new java.lang.String[] { "Type", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
