// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: GeoX.proto

package com.gg.gate.gRPC.proto;

public final class GeoXOuterClass {
    private GeoXOuterClass() {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {}

    public interface PositionOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Position)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional float lat = 1;</code>
         */
        float getLat();

        /**
         * <code>optional float lng = 2;</code>
         */
        float getLng();

        /**
         * <code>optional int32 level = 3;</code>
         */
        int getLevel();
    }
    /**
     * Protobuf type {@code Position}
     */
    public static final class Position extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:Position)
            PositionOrBuilder {
        // Use Position.newBuilder() to construct.
        private Position(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Position() {
            lat_ = 0F;
            lng_ = 0F;
            level_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Position(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 13: {

                            lat_ = input.readFloat();
                            break;
                        }
                        case 21: {

                            lng_ = input.readFloat();
                            break;
                        }
                        case 24: {

                            level_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
                throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
                        .setUnfinishedMessage(this));
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.gg.gate.gRPC.proto.GeoXOuterClass.internal_static_Position_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.gg.gate.gRPC.proto.GeoXOuterClass.internal_static_Position_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.gg.gate.gRPC.proto.GeoXOuterClass.Position.class,
                            com.gg.gate.gRPC.proto.GeoXOuterClass.Position.Builder.class);
        }

        public static final int LAT_FIELD_NUMBER = 1;
        private float lat_;

        /**
         * <code>optional float lat = 1;</code>
         */
        public float getLat() {
            return lat_;
        }

        public static final int LNG_FIELD_NUMBER = 2;
        private float lng_;

        /**
         * <code>optional float lng = 2;</code>
         */
        public float getLng() {
            return lng_;
        }

        public static final int LEVEL_FIELD_NUMBER = 3;
        private int level_;

        /**
         * <code>optional int32 level = 3;</code>
         */
        public int getLevel() {
            return level_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (lat_ != 0F) {
                output.writeFloat(1, lat_);
            }
            if (lng_ != 0F) {
                output.writeFloat(2, lng_);
            }
            if (level_ != 0) {
                output.writeInt32(3, level_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (lat_ != 0F) {
                size += com.google.protobuf.CodedOutputStream.computeFloatSize(1, lat_);
            }
            if (lng_ != 0F) {
                size += com.google.protobuf.CodedOutputStream.computeFloatSize(2, lng_);
            }
            if (level_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, level_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Position parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Position parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Position parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Position parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Position parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Position parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Position parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Position parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Position parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Position parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.gg.gate.gRPC.proto.GeoXOuterClass.Position prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Position}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Position)
                com.gg.gate.gRPC.proto.GeoXOuterClass.PositionOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.gg.gate.gRPC.proto.GeoXOuterClass.internal_static_Position_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.gg.gate.gRPC.proto.GeoXOuterClass.internal_static_Position_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.gg.gate.gRPC.proto.GeoXOuterClass.Position.class,
                                com.gg.gate.gRPC.proto.GeoXOuterClass.Position.Builder.class);
            }

            // Construct using com.gg.gate.gRPC.proto.GeoXOuterClass.Position.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                lat_ = 0F;

                lng_ = 0F;

                level_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.gg.gate.gRPC.proto.GeoXOuterClass.internal_static_Position_descriptor;
            }

            public com.gg.gate.gRPC.proto.GeoXOuterClass.Position getDefaultInstanceForType() {
                return com.gg.gate.gRPC.proto.GeoXOuterClass.Position.getDefaultInstance();
            }

            public com.gg.gate.gRPC.proto.GeoXOuterClass.Position build() {
                com.gg.gate.gRPC.proto.GeoXOuterClass.Position result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.gg.gate.gRPC.proto.GeoXOuterClass.Position buildPartial() {
                com.gg.gate.gRPC.proto.GeoXOuterClass.Position result =
                        new com.gg.gate.gRPC.proto.GeoXOuterClass.Position(this);
                result.lat_ = lat_;
                result.lng_ = lng_;
                result.level_ = level_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.gg.gate.gRPC.proto.GeoXOuterClass.Position) {
                    return mergeFrom((com.gg.gate.gRPC.proto.GeoXOuterClass.Position) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.gg.gate.gRPC.proto.GeoXOuterClass.Position other) {
                if (other == com.gg.gate.gRPC.proto.GeoXOuterClass.Position.getDefaultInstance())
                    return this;
                if (other.getLat() != 0F) {
                    setLat(other.getLat());
                }
                if (other.getLng() != 0F) {
                    setLng(other.getLng());
                }
                if (other.getLevel() != 0) {
                    setLevel(other.getLevel());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.gg.gate.gRPC.proto.GeoXOuterClass.Position parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.gg.gate.gRPC.proto.GeoXOuterClass.Position) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private float lat_;

            /**
             * <code>optional float lat = 1;</code>
             */
            public float getLat() {
                return lat_;
            }

            /**
             * <code>optional float lat = 1;</code>
             */
            public Builder setLat(float value) {

                lat_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional float lat = 1;</code>
             */
            public Builder clearLat() {

                lat_ = 0F;
                onChanged();
                return this;
            }

            private float lng_;

            /**
             * <code>optional float lng = 2;</code>
             */
            public float getLng() {
                return lng_;
            }

            /**
             * <code>optional float lng = 2;</code>
             */
            public Builder setLng(float value) {

                lng_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional float lng = 2;</code>
             */
            public Builder clearLng() {

                lng_ = 0F;
                onChanged();
                return this;
            }

            private int level_;

            /**
             * <code>optional int32 level = 3;</code>
             */
            public int getLevel() {
                return level_;
            }

            /**
             * <code>optional int32 level = 3;</code>
             */
            public Builder setLevel(int value) {

                level_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 level = 3;</code>
             */
            public Builder clearLevel() {

                level_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:Position)
        }

        // @@protoc_insertion_point(class_scope:Position)
        private static final com.gg.gate.gRPC.proto.GeoXOuterClass.Position DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.gg.gate.gRPC.proto.GeoXOuterClass.Position();
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Position getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Position> PARSER =
                new com.google.protobuf.AbstractParser<Position>() {
                    public Position parsePartialFrom(com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        try {
                            return new Position(input, extensionRegistry);
                        } catch (RuntimeException e) {
                            if (e.getCause() instanceof com.google.protobuf.InvalidProtocolBufferException) {
                                throw (com.google.protobuf.InvalidProtocolBufferException) e.getCause();
                            }
                            throw e;
                        }
                    }
                };

        public static com.google.protobuf.Parser<Position> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Position> getParserForType() {
            return PARSER;
        }

        public com.gg.gate.gRPC.proto.GeoXOuterClass.Position getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface GeohashOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Geohash)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string base32Str = 1;</code>
         */
        java.lang.String getBase32Str();

        /**
         * <code>optional string base32Str = 1;</code>
         */
        com.google.protobuf.ByteString getBase32StrBytes();
    }
    /**
     * Protobuf type {@code Geohash}
     */
    public static final class Geohash extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:Geohash)
            GeohashOrBuilder {
        // Use Geohash.newBuilder() to construct.
        private Geohash(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Geohash() {
            base32Str_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Geohash(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            base32Str_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
                throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
                        .setUnfinishedMessage(this));
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.gg.gate.gRPC.proto.GeoXOuterClass.internal_static_Geohash_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.gg.gate.gRPC.proto.GeoXOuterClass.internal_static_Geohash_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash.class,
                            com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash.Builder.class);
        }

        public static final int BASE32STR_FIELD_NUMBER = 1;
        private volatile java.lang.Object base32Str_;

        /**
         * <code>optional string base32Str = 1;</code>
         */
        public java.lang.String getBase32Str() {
            java.lang.Object ref = base32Str_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                base32Str_ = s;
                return s;
            }
        }

        /**
         * <code>optional string base32Str = 1;</code>
         */
        public com.google.protobuf.ByteString getBase32StrBytes() {
            java.lang.Object ref = base32Str_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                base32Str_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!getBase32StrBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessage.writeString(output, 1, base32Str_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!getBase32StrBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(1, base32Str_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Geohash}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Geohash)
                com.gg.gate.gRPC.proto.GeoXOuterClass.GeohashOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.gg.gate.gRPC.proto.GeoXOuterClass.internal_static_Geohash_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.gg.gate.gRPC.proto.GeoXOuterClass.internal_static_Geohash_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash.class,
                                com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash.Builder.class);
            }

            // Construct using com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                base32Str_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.gg.gate.gRPC.proto.GeoXOuterClass.internal_static_Geohash_descriptor;
            }

            public com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash getDefaultInstanceForType() {
                return com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash.getDefaultInstance();
            }

            public com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash build() {
                com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash buildPartial() {
                com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash result =
                        new com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash(this);
                result.base32Str_ = base32Str_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash) {
                    return mergeFrom((com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash other) {
                if (other == com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash.getDefaultInstance())
                    return this;
                if (!other.getBase32Str().isEmpty()) {
                    base32Str_ = other.base32Str_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object base32Str_ = "";

            /**
             * <code>optional string base32Str = 1;</code>
             */
            public java.lang.String getBase32Str() {
                java.lang.Object ref = base32Str_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    base32Str_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string base32Str = 1;</code>
             */
            public com.google.protobuf.ByteString getBase32StrBytes() {
                java.lang.Object ref = base32Str_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    base32Str_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string base32Str = 1;</code>
             */
            public Builder setBase32Str(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                base32Str_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string base32Str = 1;</code>
             */
            public Builder clearBase32Str() {

                base32Str_ = getDefaultInstance().getBase32Str();
                onChanged();
                return this;
            }

            /**
             * <code>optional string base32Str = 1;</code>
             */
            public Builder setBase32StrBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                base32Str_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:Geohash)
        }

        // @@protoc_insertion_point(class_scope:Geohash)
        private static final com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash();
        }

        public static com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Geohash> PARSER =
                new com.google.protobuf.AbstractParser<Geohash>() {
                    public Geohash parsePartialFrom(com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        try {
                            return new Geohash(input, extensionRegistry);
                        } catch (RuntimeException e) {
                            if (e.getCause() instanceof com.google.protobuf.InvalidProtocolBufferException) {
                                throw (com.google.protobuf.InvalidProtocolBufferException) e.getCause();
                            }
                            throw e;
                        }
                    }
                };

        public static com.google.protobuf.Parser<Geohash> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Geohash> getParserForType() {
            return PARSER;
        }

        public com.gg.gate.gRPC.proto.GeoXOuterClass.Geohash getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_Position_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_Position_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor internal_static_Geohash_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_Geohash_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData =
                {"\n\nGeoX.proto\"3\n\010Position\022\013\n\003lat\030\001 \001(\002\022\013\n"
                        + "\003lng\030\002 \001(\002\022\r\n\005level\030\003 \001(\005\"\034\n\007Geohash\022\021\n\t"
                        + "base32Str\030\001 \001(\t2*\n\004GeoX\022\"\n\013calcGeohash\022\t"
                        + ".Position\032\010.GeohashB\032\n\026com.gg.gate.gRPC." + "protoH\001b\006proto3"};
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_Position_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_Position_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Position_descriptor, new java.lang.String[] {"Lat", "Lng", "Level",});
        internal_static_Geohash_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_Geohash_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Geohash_descriptor, new java.lang.String[] {"Base32Str",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
