// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: GateRpc.proto

package com.gg.protocol.gate;

public final class GateRpc {
    private GateRpc() {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {}

    public interface MessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:RequestMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional int32 type = 1;</code>
         *
         * <pre>
         * msg type
         * </pre>
         */
        int getType();

        /**
         * <code>optional int32 sid = 2;</code>
         *
         * <pre>
         * session id
         * </pre>
         */
        int getSid();

        /**
         * <code>optional int32 rid = 3;</code>
         *
         * <pre>
         * request id
         * </pre>
         */
        int getRid();

        /**
         * <code>optional string instance = 4;</code>
         */
        java.lang.String getInstance();

        /**
         * <code>optional string instance = 4;</code>
         */
        com.google.protobuf.ByteString getInstanceBytes();

        /**
         * <code>optional string method = 5;</code>
         */
        java.lang.String getMethod();

        /**
         * <code>optional string method = 5;</code>
         */
        com.google.protobuf.ByteString getMethodBytes();

        /**
         * <code>optional bytes payload = 6;</code>
         */
        com.google.protobuf.ByteString getPayload();
    }
    /**
     * Protobuf type {@code RequestMessage}
     */
    public static final class Message extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:RequestMessage)
            MessageOrBuilder {
        // Use RequestMessage.newBuilder() to construct.
        private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Message() {
            type_ = 0;
            sid_ = 0;
            rid_ = 0;
            instance_ = "";
            method_ = "";
            payload_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Message(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            type_ = input.readInt32();
                            break;
                        }
                        case 16: {

                            sid_ = input.readInt32();
                            break;
                        }
                        case 24: {

                            rid_ = input.readInt32();
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            instance_ = s;
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            method_ = s;
                            break;
                        }
                        case 50: {

                            payload_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
                throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
                        .setUnfinishedMessage(this));
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.gg.protocol.gate.GateRpc.internal_static_Message_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.gg.protocol.gate.GateRpc.internal_static_Message_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.gg.protocol.gate.GateRpc.Message.class,
                            com.gg.protocol.gate.GateRpc.Message.Builder.class);
        }

        public static final int TYPE_FIELD_NUMBER = 1;
        private int type_;

        /**
         * <code>optional int32 type = 1;</code>
         *
         * <pre>
         * msg type
         * </pre>
         */
        public int getType() {
            return type_;
        }

        public static final int SID_FIELD_NUMBER = 2;
        private int sid_;

        /**
         * <code>optional int32 sid = 2;</code>
         *
         * <pre>
         * session id
         * </pre>
         */
        public int getSid() {
            return sid_;
        }

        public static final int RID_FIELD_NUMBER = 3;
        private int rid_;

        /**
         * <code>optional int32 rid = 3;</code>
         *
         * <pre>
         * request id
         * </pre>
         */
        public int getRid() {
            return rid_;
        }

        public static final int INSTANCE_FIELD_NUMBER = 4;
        private volatile java.lang.Object instance_;

        /**
         * <code>optional string instance = 4;</code>
         */
        public java.lang.String getInstance() {
            java.lang.Object ref = instance_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                instance_ = s;
                return s;
            }
        }

        /**
         * <code>optional string instance = 4;</code>
         */
        public com.google.protobuf.ByteString getInstanceBytes() {
            java.lang.Object ref = instance_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                instance_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int METHOD_FIELD_NUMBER = 5;
        private volatile java.lang.Object method_;

        /**
         * <code>optional string method = 5;</code>
         */
        public java.lang.String getMethod() {
            java.lang.Object ref = method_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                method_ = s;
                return s;
            }
        }

        /**
         * <code>optional string method = 5;</code>
         */
        public com.google.protobuf.ByteString getMethodBytes() {
            java.lang.Object ref = method_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                method_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PAYLOAD_FIELD_NUMBER = 6;
        private com.google.protobuf.ByteString payload_;

        /**
         * <code>optional bytes payload = 6;</code>
         */
        public com.google.protobuf.ByteString getPayload() {
            return payload_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (type_ != 0) {
                output.writeInt32(1, type_);
            }
            if (sid_ != 0) {
                output.writeInt32(2, sid_);
            }
            if (rid_ != 0) {
                output.writeInt32(3, rid_);
            }
            if (!getInstanceBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessage.writeString(output, 4, instance_);
            }
            if (!getMethodBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessage.writeString(output, 5, method_);
            }
            if (!payload_.isEmpty()) {
                output.writeBytes(6, payload_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (type_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, type_);
            }
            if (sid_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, sid_);
            }
            if (rid_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, rid_);
            }
            if (!getInstanceBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(4, instance_);
            }
            if (!getMethodBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(5, method_);
            }
            if (!payload_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(6, payload_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        public static com.gg.protocol.gate.GateRpc.Message parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.gg.protocol.gate.GateRpc.Message parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.gg.protocol.gate.GateRpc.Message parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.gg.protocol.gate.GateRpc.Message parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.gg.protocol.gate.GateRpc.Message parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.gg.protocol.gate.GateRpc.Message parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.gg.protocol.gate.GateRpc.Message parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.gg.protocol.gate.GateRpc.Message parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.gg.protocol.gate.GateRpc.Message parseFrom(com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.gg.protocol.gate.GateRpc.Message parseFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.gg.protocol.gate.GateRpc.Message prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code RequestMessage}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:RequestMessage)
                com.gg.protocol.gate.GateRpc.MessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.gg.protocol.gate.GateRpc.internal_static_Message_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.gg.protocol.gate.GateRpc.internal_static_Message_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.gg.protocol.gate.GateRpc.Message.class,
                                com.gg.protocol.gate.GateRpc.Message.Builder.class);
            }

            // Construct using com.gg.protocol.gate.GateRpc.RequestMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                type_ = 0;

                sid_ = 0;

                rid_ = 0;

                instance_ = "";

                method_ = "";

                payload_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.gg.protocol.gate.GateRpc.internal_static_Message_descriptor;
            }

            public com.gg.protocol.gate.GateRpc.Message getDefaultInstanceForType() {
                return com.gg.protocol.gate.GateRpc.Message.getDefaultInstance();
            }

            public com.gg.protocol.gate.GateRpc.Message build() {
                com.gg.protocol.gate.GateRpc.Message result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.gg.protocol.gate.GateRpc.Message buildPartial() {
                com.gg.protocol.gate.GateRpc.Message result = new com.gg.protocol.gate.GateRpc.Message(this);
                result.type_ = type_;
                result.sid_ = sid_;
                result.rid_ = rid_;
                result.instance_ = instance_;
                result.method_ = method_;
                result.payload_ = payload_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.gg.protocol.gate.GateRpc.Message) {
                    return mergeFrom((com.gg.protocol.gate.GateRpc.Message) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.gg.protocol.gate.GateRpc.Message other) {
                if (other == com.gg.protocol.gate.GateRpc.Message.getDefaultInstance())
                    return this;
                if (other.getType() != 0) {
                    setType(other.getType());
                }
                if (other.getSid() != 0) {
                    setSid(other.getSid());
                }
                if (other.getRid() != 0) {
                    setRid(other.getRid());
                }
                if (!other.getInstance().isEmpty()) {
                    instance_ = other.instance_;
                    onChanged();
                }
                if (!other.getMethod().isEmpty()) {
                    method_ = other.method_;
                    onChanged();
                }
                if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
                    setPayload(other.getPayload());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.gg.protocol.gate.GateRpc.Message parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.gg.protocol.gate.GateRpc.Message) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int type_;

            /**
             * <code>optional int32 type = 1;</code>
             *
             * <pre>
             * msg type
             * </pre>
             */
            public int getType() {
                return type_;
            }

            /**
             * <code>optional int32 type = 1;</code>
             *
             * <pre>
             * msg type
             * </pre>
             */
            public Builder setType(int value) {

                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 type = 1;</code>
             *
             * <pre>
             * msg type
             * </pre>
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private int sid_;

            /**
             * <code>optional int32 sid = 2;</code>
             *
             * <pre>
             * session id
             * </pre>
             */
            public int getSid() {
                return sid_;
            }

            /**
             * <code>optional int32 sid = 2;</code>
             *
             * <pre>
             * session id
             * </pre>
             */
            public Builder setSid(int value) {

                sid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 sid = 2;</code>
             *
             * <pre>
             * session id
             * </pre>
             */
            public Builder clearSid() {

                sid_ = 0;
                onChanged();
                return this;
            }

            private int rid_;

            /**
             * <code>optional int32 rid = 3;</code>
             *
             * <pre>
             * request id
             * </pre>
             */
            public int getRid() {
                return rid_;
            }

            /**
             * <code>optional int32 rid = 3;</code>
             *
             * <pre>
             * request id
             * </pre>
             */
            public Builder setRid(int value) {

                rid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 rid = 3;</code>
             *
             * <pre>
             * request id
             * </pre>
             */
            public Builder clearRid() {

                rid_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object instance_ = "";

            /**
             * <code>optional string instance = 4;</code>
             */
            public java.lang.String getInstance() {
                java.lang.Object ref = instance_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    instance_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string instance = 4;</code>
             */
            public com.google.protobuf.ByteString getInstanceBytes() {
                java.lang.Object ref = instance_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    instance_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string instance = 4;</code>
             */
            public Builder setInstance(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                instance_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string instance = 4;</code>
             */
            public Builder clearInstance() {

                instance_ = getDefaultInstance().getInstance();
                onChanged();
                return this;
            }

            /**
             * <code>optional string instance = 4;</code>
             */
            public Builder setInstanceBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                instance_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object method_ = "";

            /**
             * <code>optional string method = 5;</code>
             */
            public java.lang.String getMethod() {
                java.lang.Object ref = method_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    method_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string method = 5;</code>
             */
            public com.google.protobuf.ByteString getMethodBytes() {
                java.lang.Object ref = method_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    method_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string method = 5;</code>
             */
            public Builder setMethod(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                method_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string method = 5;</code>
             */
            public Builder clearMethod() {

                method_ = getDefaultInstance().getMethod();
                onChanged();
                return this;
            }

            /**
             * <code>optional string method = 5;</code>
             */
            public Builder setMethodBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                method_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>optional bytes payload = 6;</code>
             */
            public com.google.protobuf.ByteString getPayload() {
                return payload_;
            }

            /**
             * <code>optional bytes payload = 6;</code>
             */
            public Builder setPayload(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                payload_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes payload = 6;</code>
             */
            public Builder clearPayload() {

                payload_ = getDefaultInstance().getPayload();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:RequestMessage)
        }

        // @@protoc_insertion_point(class_scope:RequestMessage)
        private static final com.gg.protocol.gate.GateRpc.Message DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.gg.protocol.gate.GateRpc.Message();
        }

        public static com.gg.protocol.gate.GateRpc.Message getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Message> PARSER =
                new com.google.protobuf.AbstractParser<Message>() {
                    public Message parsePartialFrom(com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        try {
                            return new Message(input, extensionRegistry);
                        } catch (RuntimeException e) {
                            if (e.getCause() instanceof com.google.protobuf.InvalidProtocolBufferException) {
                                throw (com.google.protobuf.InvalidProtocolBufferException) e.getCause();
                            }
                            throw e;
                        }
                    }
                };

        public static com.google.protobuf.Parser<Message> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Message> getParserForType() {
            return PARSER;
        }

        public com.gg.protocol.gate.GateRpc.Message getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_Message_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_Message_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {"\n\rGateRpc.proto\"d\n\007Message\022\014\n\004type\030\001 \001(\005"
                + "\022\013\n\003sid\030\002 \001(\005\022\013\n\003rid\030\003 \001(\005\022\020\n\010instance\030\004"
                + " \001(\t\022\016\n\006method\030\005 \001(\t\022\017\n\007payload\030\006 \001(\0142.\n"
                + "\nGateTunnel\022 \n\006tunnel\022\010.RequestMessage\032\010.Messag"
                + "e(\0010\001B\026\n\024com.gg.protocol.gateb\006proto3"};
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_Message_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_Message_fieldAccessorTable =
                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_Message_descriptor,
                        new java.lang.String[] {"Type", "Sid", "Rid", "Instance", "Method", "Payload",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
