// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Harbor.proto

package com.gg.core.harbor.protocol;

public final class HarborOuterClass {
  private HarborOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * handshake
     * </pre>
     *
     * <code>Handshake = 0;</code>
     */
    Handshake(0),
    /**
     * <pre>
     * request, need response
     * </pre>
     *
     * <code>Request = 1;</code>
     */
    Request(1),
    /**
     * <pre>
     * response
     * </pre>
     *
     * <code>Response = 2;</code>
     */
    Response(2),
    /**
     * <pre>
     * post, need not response
     * </pre>
     *
     * <code>Post = 3;</code>
     */
    Post(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * handshake
     * </pre>
     *
     * <code>Handshake = 0;</code>
     */
    public static final int Handshake_VALUE = 0;
    /**
     * <pre>
     * request, need response
     * </pre>
     *
     * <code>Request = 1;</code>
     */
    public static final int Request_VALUE = 1;
    /**
     * <pre>
     * response
     * </pre>
     *
     * <code>Response = 2;</code>
     */
    public static final int Response_VALUE = 2;
    /**
     * <pre>
     * post, need not response
     * </pre>
     *
     * <code>Post = 3;</code>
     */
    public static final int Post_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return Handshake;
        case 1: return Request;
        case 2: return Response;
        case 3: return Post;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.gg.core.harbor.protocol.HarborOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageType)
  }

  public interface ServiceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Service)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * service name
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * service name
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * host addr
     * </pre>
     *
     * <code>optional string host = 2;</code>
     */
    java.lang.String getHost();
    /**
     * <pre>
     * host addr
     * </pre>
     *
     * <code>optional string host = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <pre>
     * port
     * </pre>
     *
     * <code>optional int32 port = 3;</code>
     */
    int getPort();
  }
  /**
   * Protobuf type {@code Service}
   */
  public  static final class Service extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Service)
      ServiceOrBuilder {
    // Use Service.newBuilder() to construct.
    private Service(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Service() {
      name_ = "";
      host_ = "";
      port_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Service(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 24: {

              port_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_Service_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_Service_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gg.core.harbor.protocol.HarborOuterClass.Service.class, com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * service name
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * service name
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOST_FIELD_NUMBER = 2;
    private volatile java.lang.Object host_;
    /**
     * <pre>
     * host addr
     * </pre>
     *
     * <code>optional string host = 2;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * host addr
     * </pre>
     *
     * <code>optional string host = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <pre>
     * port
     * </pre>
     *
     * <code>optional int32 port = 3;</code>
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, host_);
      }
      if (port_ != 0) {
        output.writeInt32(3, port_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gg.core.harbor.protocol.HarborOuterClass.Service)) {
        return super.equals(obj);
      }
      com.gg.core.harbor.protocol.HarborOuterClass.Service other = (com.gg.core.harbor.protocol.HarborOuterClass.Service) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getHost()
          .equals(other.getHost());
      result = result && (getPort()
          == other.getPort());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gg.core.harbor.protocol.HarborOuterClass.Service parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.Service parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.Service parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.Service parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.Service parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.Service parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.Service parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.Service parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.Service parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.Service parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gg.core.harbor.protocol.HarborOuterClass.Service prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Service}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Service)
        com.gg.core.harbor.protocol.HarborOuterClass.ServiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_Service_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_Service_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gg.core.harbor.protocol.HarborOuterClass.Service.class, com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder.class);
      }

      // Construct using com.gg.core.harbor.protocol.HarborOuterClass.Service.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        host_ = "";

        port_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_Service_descriptor;
      }

      public com.gg.core.harbor.protocol.HarborOuterClass.Service getDefaultInstanceForType() {
        return com.gg.core.harbor.protocol.HarborOuterClass.Service.getDefaultInstance();
      }

      public com.gg.core.harbor.protocol.HarborOuterClass.Service build() {
        com.gg.core.harbor.protocol.HarborOuterClass.Service result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gg.core.harbor.protocol.HarborOuterClass.Service buildPartial() {
        com.gg.core.harbor.protocol.HarborOuterClass.Service result = new com.gg.core.harbor.protocol.HarborOuterClass.Service(this);
        result.name_ = name_;
        result.host_ = host_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gg.core.harbor.protocol.HarborOuterClass.Service) {
          return mergeFrom((com.gg.core.harbor.protocol.HarborOuterClass.Service)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gg.core.harbor.protocol.HarborOuterClass.Service other) {
        if (other == com.gg.core.harbor.protocol.HarborOuterClass.Service.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gg.core.harbor.protocol.HarborOuterClass.Service parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gg.core.harbor.protocol.HarborOuterClass.Service) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * service name
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * service name
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * service name
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * service name
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * service name
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <pre>
       * host addr
       * </pre>
       *
       * <code>optional string host = 2;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * host addr
       * </pre>
       *
       * <code>optional string host = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * host addr
       * </pre>
       *
       * <code>optional string host = 2;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * host addr
       * </pre>
       *
       * <code>optional string host = 2;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * host addr
       * </pre>
       *
       * <code>optional string host = 2;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <pre>
       * port
       * </pre>
       *
       * <code>optional int32 port = 3;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <pre>
       * port
       * </pre>
       *
       * <code>optional int32 port = 3;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * port
       * </pre>
       *
       * <code>optional int32 port = 3;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Service)
    }

    // @@protoc_insertion_point(class_scope:Service)
    private static final com.gg.core.harbor.protocol.HarborOuterClass.Service DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gg.core.harbor.protocol.HarborOuterClass.Service();
    }

    public static com.gg.core.harbor.protocol.HarborOuterClass.Service getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Service>
        PARSER = new com.google.protobuf.AbstractParser<Service>() {
      public Service parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Service(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Service> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Service> getParserForType() {
      return PARSER;
    }

    public com.gg.core.harbor.protocol.HarborOuterClass.Service getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HandshakeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HandshakeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Service source = 1;</code>
     */
    boolean hasSource();
    /**
     * <code>optional .Service source = 1;</code>
     */
    com.gg.core.harbor.protocol.HarborOuterClass.Service getSource();
    /**
     * <code>optional .Service source = 1;</code>
     */
    com.gg.core.harbor.protocol.HarborOuterClass.ServiceOrBuilder getSourceOrBuilder();
  }
  /**
   * Protobuf type {@code HandshakeMessage}
   */
  public  static final class HandshakeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HandshakeMessage)
      HandshakeMessageOrBuilder {
    // Use HandshakeMessage.newBuilder() to construct.
    private HandshakeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HandshakeMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HandshakeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder subBuilder = null;
              if (source_ != null) {
                subBuilder = source_.toBuilder();
              }
              source_ = input.readMessage(com.gg.core.harbor.protocol.HarborOuterClass.Service.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(source_);
                source_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_HandshakeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_HandshakeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage.class, com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage.Builder.class);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    private com.gg.core.harbor.protocol.HarborOuterClass.Service source_;
    /**
     * <code>optional .Service source = 1;</code>
     */
    public boolean hasSource() {
      return source_ != null;
    }
    /**
     * <code>optional .Service source = 1;</code>
     */
    public com.gg.core.harbor.protocol.HarborOuterClass.Service getSource() {
      return source_ == null ? com.gg.core.harbor.protocol.HarborOuterClass.Service.getDefaultInstance() : source_;
    }
    /**
     * <code>optional .Service source = 1;</code>
     */
    public com.gg.core.harbor.protocol.HarborOuterClass.ServiceOrBuilder getSourceOrBuilder() {
      return getSource();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (source_ != null) {
        output.writeMessage(1, getSource());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (source_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSource());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage)) {
        return super.equals(obj);
      }
      com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage other = (com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage) obj;

      boolean result = true;
      result = result && (hasSource() == other.hasSource());
      if (hasSource()) {
        result = result && getSource()
            .equals(other.getSource());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSource()) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSource().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HandshakeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HandshakeMessage)
        com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_HandshakeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_HandshakeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage.class, com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage.Builder.class);
      }

      // Construct using com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (sourceBuilder_ == null) {
          source_ = null;
        } else {
          source_ = null;
          sourceBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_HandshakeMessage_descriptor;
      }

      public com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage getDefaultInstanceForType() {
        return com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage.getDefaultInstance();
      }

      public com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage build() {
        com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage buildPartial() {
        com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage result = new com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage(this);
        if (sourceBuilder_ == null) {
          result.source_ = source_;
        } else {
          result.source_ = sourceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage) {
          return mergeFrom((com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage other) {
        if (other == com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage.getDefaultInstance()) return this;
        if (other.hasSource()) {
          mergeSource(other.getSource());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.gg.core.harbor.protocol.HarborOuterClass.Service source_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.gg.core.harbor.protocol.HarborOuterClass.Service, com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder, com.gg.core.harbor.protocol.HarborOuterClass.ServiceOrBuilder> sourceBuilder_;
      /**
       * <code>optional .Service source = 1;</code>
       */
      public boolean hasSource() {
        return sourceBuilder_ != null || source_ != null;
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public com.gg.core.harbor.protocol.HarborOuterClass.Service getSource() {
        if (sourceBuilder_ == null) {
          return source_ == null ? com.gg.core.harbor.protocol.HarborOuterClass.Service.getDefaultInstance() : source_;
        } else {
          return sourceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public Builder setSource(com.gg.core.harbor.protocol.HarborOuterClass.Service value) {
        if (sourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          source_ = value;
          onChanged();
        } else {
          sourceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public Builder setSource(
          com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder builderForValue) {
        if (sourceBuilder_ == null) {
          source_ = builderForValue.build();
          onChanged();
        } else {
          sourceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public Builder mergeSource(com.gg.core.harbor.protocol.HarborOuterClass.Service value) {
        if (sourceBuilder_ == null) {
          if (source_ != null) {
            source_ =
              com.gg.core.harbor.protocol.HarborOuterClass.Service.newBuilder(source_).mergeFrom(value).buildPartial();
          } else {
            source_ = value;
          }
          onChanged();
        } else {
          sourceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public Builder clearSource() {
        if (sourceBuilder_ == null) {
          source_ = null;
          onChanged();
        } else {
          source_ = null;
          sourceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder getSourceBuilder() {
        
        onChanged();
        return getSourceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      public com.gg.core.harbor.protocol.HarborOuterClass.ServiceOrBuilder getSourceOrBuilder() {
        if (sourceBuilder_ != null) {
          return sourceBuilder_.getMessageOrBuilder();
        } else {
          return source_ == null ?
              com.gg.core.harbor.protocol.HarborOuterClass.Service.getDefaultInstance() : source_;
        }
      }
      /**
       * <code>optional .Service source = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.gg.core.harbor.protocol.HarborOuterClass.Service, com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder, com.gg.core.harbor.protocol.HarborOuterClass.ServiceOrBuilder> 
          getSourceFieldBuilder() {
        if (sourceBuilder_ == null) {
          sourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.gg.core.harbor.protocol.HarborOuterClass.Service, com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder, com.gg.core.harbor.protocol.HarborOuterClass.ServiceOrBuilder>(
                  getSource(),
                  getParentForChildren(),
                  isClean());
          source_ = null;
        }
        return sourceBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:HandshakeMessage)
    }

    // @@protoc_insertion_point(class_scope:HandshakeMessage)
    private static final com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage();
    }

    public static com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HandshakeMessage>
        PARSER = new com.google.protobuf.AbstractParser<HandshakeMessage>() {
      public HandshakeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HandshakeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HandshakeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HandshakeMessage> getParserForType() {
      return PARSER;
    }

    public com.gg.core.harbor.protocol.HarborOuterClass.HandshakeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HarborMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HarborMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * msg type
     * </pre>
     *
     * <code>optional .MessageType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * msg type
     * </pre>
     *
     * <code>optional .MessageType type = 1;</code>
     */
    com.gg.core.harbor.protocol.HarborOuterClass.MessageType getType();

    /**
     * <pre>
     * session id
     * </pre>
     *
     * <code>optional int32 sid = 2;</code>
     */
    int getSid();

    /**
     * <pre>
     * request id
     * </pre>
     *
     * <code>optional int32 rid = 3;</code>
     */
    int getRid();

    /**
     * <code>optional .Service source = 4;</code>
     */
    boolean hasSource();
    /**
     * <code>optional .Service source = 4;</code>
     */
    com.gg.core.harbor.protocol.HarborOuterClass.Service getSource();
    /**
     * <code>optional .Service source = 4;</code>
     */
    com.gg.core.harbor.protocol.HarborOuterClass.ServiceOrBuilder getSourceOrBuilder();

    /**
     * <code>optional string instance = 5;</code>
     */
    java.lang.String getInstance();
    /**
     * <code>optional string instance = 5;</code>
     */
    com.google.protobuf.ByteString
        getInstanceBytes();

    /**
     * <code>optional string method = 6;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>optional string method = 6;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>repeated bytes payload = 7;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getPayloadList();
    /**
     * <code>repeated bytes payload = 7;</code>
     */
    int getPayloadCount();
    /**
     * <code>repeated bytes payload = 7;</code>
     */
    com.google.protobuf.ByteString getPayload(int index);
  }
  /**
   * Protobuf type {@code HarborMessage}
   */
  public  static final class HarborMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HarborMessage)
      HarborMessageOrBuilder {
    // Use HarborMessage.newBuilder() to construct.
    private HarborMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HarborMessage() {
      type_ = 0;
      sid_ = 0;
      rid_ = 0;
      instance_ = "";
      method_ = "";
      payload_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HarborMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {

              sid_ = input.readInt32();
              break;
            }
            case 24: {

              rid_ = input.readInt32();
              break;
            }
            case 34: {
              com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder subBuilder = null;
              if (source_ != null) {
                subBuilder = source_.toBuilder();
              }
              source_ = input.readMessage(com.gg.core.harbor.protocol.HarborOuterClass.Service.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(source_);
                source_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              instance_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                payload_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000040;
              }
              payload_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          payload_ = java.util.Collections.unmodifiableList(payload_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_HarborMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_HarborMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage.class, com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * msg type
     * </pre>
     *
     * <code>optional .MessageType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * msg type
     * </pre>
     *
     * <code>optional .MessageType type = 1;</code>
     */
    public com.gg.core.harbor.protocol.HarborOuterClass.MessageType getType() {
      com.gg.core.harbor.protocol.HarborOuterClass.MessageType result = com.gg.core.harbor.protocol.HarborOuterClass.MessageType.valueOf(type_);
      return result == null ? com.gg.core.harbor.protocol.HarborOuterClass.MessageType.UNRECOGNIZED : result;
    }

    public static final int SID_FIELD_NUMBER = 2;
    private int sid_;
    /**
     * <pre>
     * session id
     * </pre>
     *
     * <code>optional int32 sid = 2;</code>
     */
    public int getSid() {
      return sid_;
    }

    public static final int RID_FIELD_NUMBER = 3;
    private int rid_;
    /**
     * <pre>
     * request id
     * </pre>
     *
     * <code>optional int32 rid = 3;</code>
     */
    public int getRid() {
      return rid_;
    }

    public static final int SOURCE_FIELD_NUMBER = 4;
    private com.gg.core.harbor.protocol.HarborOuterClass.Service source_;
    /**
     * <code>optional .Service source = 4;</code>
     */
    public boolean hasSource() {
      return source_ != null;
    }
    /**
     * <code>optional .Service source = 4;</code>
     */
    public com.gg.core.harbor.protocol.HarborOuterClass.Service getSource() {
      return source_ == null ? com.gg.core.harbor.protocol.HarborOuterClass.Service.getDefaultInstance() : source_;
    }
    /**
     * <code>optional .Service source = 4;</code>
     */
    public com.gg.core.harbor.protocol.HarborOuterClass.ServiceOrBuilder getSourceOrBuilder() {
      return getSource();
    }

    public static final int INSTANCE_FIELD_NUMBER = 5;
    private volatile java.lang.Object instance_;
    /**
     * <code>optional string instance = 5;</code>
     */
    public java.lang.String getInstance() {
      java.lang.Object ref = instance_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instance_ = s;
        return s;
      }
    }
    /**
     * <code>optional string instance = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInstanceBytes() {
      java.lang.Object ref = instance_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 6;
    private volatile java.lang.Object method_;
    /**
     * <code>optional string method = 6;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>optional string method = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 7;
    private java.util.List<com.google.protobuf.ByteString> payload_;
    /**
     * <code>repeated bytes payload = 7;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getPayloadList() {
      return payload_;
    }
    /**
     * <code>repeated bytes payload = 7;</code>
     */
    public int getPayloadCount() {
      return payload_.size();
    }
    /**
     * <code>repeated bytes payload = 7;</code>
     */
    public com.google.protobuf.ByteString getPayload(int index) {
      return payload_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.gg.core.harbor.protocol.HarborOuterClass.MessageType.Handshake.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (sid_ != 0) {
        output.writeInt32(2, sid_);
      }
      if (rid_ != 0) {
        output.writeInt32(3, rid_);
      }
      if (source_ != null) {
        output.writeMessage(4, getSource());
      }
      if (!getInstanceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, instance_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, method_);
      }
      for (int i = 0; i < payload_.size(); i++) {
        output.writeBytes(7, payload_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.gg.core.harbor.protocol.HarborOuterClass.MessageType.Handshake.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (sid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sid_);
      }
      if (rid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rid_);
      }
      if (source_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSource());
      }
      if (!getInstanceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, instance_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, method_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < payload_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(payload_.get(i));
        }
        size += dataSize;
        size += 1 * getPayloadList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage)) {
        return super.equals(obj);
      }
      com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage other = (com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (getSid()
          == other.getSid());
      result = result && (getRid()
          == other.getRid());
      result = result && (hasSource() == other.hasSource());
      if (hasSource()) {
        result = result && getSource()
            .equals(other.getSource());
      }
      result = result && getInstance()
          .equals(other.getInstance());
      result = result && getMethod()
          .equals(other.getMethod());
      result = result && getPayloadList()
          .equals(other.getPayloadList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SID_FIELD_NUMBER;
      hash = (53 * hash) + getSid();
      hash = (37 * hash) + RID_FIELD_NUMBER;
      hash = (53 * hash) + getRid();
      if (hasSource()) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSource().hashCode();
      }
      hash = (37 * hash) + INSTANCE_FIELD_NUMBER;
      hash = (53 * hash) + getInstance().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      if (getPayloadCount() > 0) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayloadList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HarborMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HarborMessage)
        com.gg.core.harbor.protocol.HarborOuterClass.HarborMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_HarborMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_HarborMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage.class, com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage.Builder.class);
      }

      // Construct using com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        sid_ = 0;

        rid_ = 0;

        if (sourceBuilder_ == null) {
          source_ = null;
        } else {
          source_ = null;
          sourceBuilder_ = null;
        }
        instance_ = "";

        method_ = "";

        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gg.core.harbor.protocol.HarborOuterClass.internal_static_HarborMessage_descriptor;
      }

      public com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage getDefaultInstanceForType() {
        return com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage.getDefaultInstance();
      }

      public com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage build() {
        com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage buildPartial() {
        com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage result = new com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.sid_ = sid_;
        result.rid_ = rid_;
        if (sourceBuilder_ == null) {
          result.source_ = source_;
        } else {
          result.source_ = sourceBuilder_.build();
        }
        result.instance_ = instance_;
        result.method_ = method_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          payload_ = java.util.Collections.unmodifiableList(payload_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage) {
          return mergeFrom((com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage other) {
        if (other == com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getSid() != 0) {
          setSid(other.getSid());
        }
        if (other.getRid() != 0) {
          setRid(other.getRid());
        }
        if (other.hasSource()) {
          mergeSource(other.getSource());
        }
        if (!other.getInstance().isEmpty()) {
          instance_ = other.instance_;
          onChanged();
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (!other.payload_.isEmpty()) {
          if (payload_.isEmpty()) {
            payload_ = other.payload_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensurePayloadIsMutable();
            payload_.addAll(other.payload_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <pre>
       * msg type
       * </pre>
       *
       * <code>optional .MessageType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * msg type
       * </pre>
       *
       * <code>optional .MessageType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * msg type
       * </pre>
       *
       * <code>optional .MessageType type = 1;</code>
       */
      public com.gg.core.harbor.protocol.HarborOuterClass.MessageType getType() {
        com.gg.core.harbor.protocol.HarborOuterClass.MessageType result = com.gg.core.harbor.protocol.HarborOuterClass.MessageType.valueOf(type_);
        return result == null ? com.gg.core.harbor.protocol.HarborOuterClass.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * msg type
       * </pre>
       *
       * <code>optional .MessageType type = 1;</code>
       */
      public Builder setType(com.gg.core.harbor.protocol.HarborOuterClass.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * msg type
       * </pre>
       *
       * <code>optional .MessageType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int sid_ ;
      /**
       * <pre>
       * session id
       * </pre>
       *
       * <code>optional int32 sid = 2;</code>
       */
      public int getSid() {
        return sid_;
      }
      /**
       * <pre>
       * session id
       * </pre>
       *
       * <code>optional int32 sid = 2;</code>
       */
      public Builder setSid(int value) {
        
        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * session id
       * </pre>
       *
       * <code>optional int32 sid = 2;</code>
       */
      public Builder clearSid() {
        
        sid_ = 0;
        onChanged();
        return this;
      }

      private int rid_ ;
      /**
       * <pre>
       * request id
       * </pre>
       *
       * <code>optional int32 rid = 3;</code>
       */
      public int getRid() {
        return rid_;
      }
      /**
       * <pre>
       * request id
       * </pre>
       *
       * <code>optional int32 rid = 3;</code>
       */
      public Builder setRid(int value) {
        
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * request id
       * </pre>
       *
       * <code>optional int32 rid = 3;</code>
       */
      public Builder clearRid() {
        
        rid_ = 0;
        onChanged();
        return this;
      }

      private com.gg.core.harbor.protocol.HarborOuterClass.Service source_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.gg.core.harbor.protocol.HarborOuterClass.Service, com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder, com.gg.core.harbor.protocol.HarborOuterClass.ServiceOrBuilder> sourceBuilder_;
      /**
       * <code>optional .Service source = 4;</code>
       */
      public boolean hasSource() {
        return sourceBuilder_ != null || source_ != null;
      }
      /**
       * <code>optional .Service source = 4;</code>
       */
      public com.gg.core.harbor.protocol.HarborOuterClass.Service getSource() {
        if (sourceBuilder_ == null) {
          return source_ == null ? com.gg.core.harbor.protocol.HarborOuterClass.Service.getDefaultInstance() : source_;
        } else {
          return sourceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Service source = 4;</code>
       */
      public Builder setSource(com.gg.core.harbor.protocol.HarborOuterClass.Service value) {
        if (sourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          source_ = value;
          onChanged();
        } else {
          sourceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Service source = 4;</code>
       */
      public Builder setSource(
          com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder builderForValue) {
        if (sourceBuilder_ == null) {
          source_ = builderForValue.build();
          onChanged();
        } else {
          sourceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Service source = 4;</code>
       */
      public Builder mergeSource(com.gg.core.harbor.protocol.HarborOuterClass.Service value) {
        if (sourceBuilder_ == null) {
          if (source_ != null) {
            source_ =
              com.gg.core.harbor.protocol.HarborOuterClass.Service.newBuilder(source_).mergeFrom(value).buildPartial();
          } else {
            source_ = value;
          }
          onChanged();
        } else {
          sourceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Service source = 4;</code>
       */
      public Builder clearSource() {
        if (sourceBuilder_ == null) {
          source_ = null;
          onChanged();
        } else {
          source_ = null;
          sourceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Service source = 4;</code>
       */
      public com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder getSourceBuilder() {
        
        onChanged();
        return getSourceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Service source = 4;</code>
       */
      public com.gg.core.harbor.protocol.HarborOuterClass.ServiceOrBuilder getSourceOrBuilder() {
        if (sourceBuilder_ != null) {
          return sourceBuilder_.getMessageOrBuilder();
        } else {
          return source_ == null ?
              com.gg.core.harbor.protocol.HarborOuterClass.Service.getDefaultInstance() : source_;
        }
      }
      /**
       * <code>optional .Service source = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.gg.core.harbor.protocol.HarborOuterClass.Service, com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder, com.gg.core.harbor.protocol.HarborOuterClass.ServiceOrBuilder> 
          getSourceFieldBuilder() {
        if (sourceBuilder_ == null) {
          sourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.gg.core.harbor.protocol.HarborOuterClass.Service, com.gg.core.harbor.protocol.HarborOuterClass.Service.Builder, com.gg.core.harbor.protocol.HarborOuterClass.ServiceOrBuilder>(
                  getSource(),
                  getParentForChildren(),
                  isClean());
          source_ = null;
        }
        return sourceBuilder_;
      }

      private java.lang.Object instance_ = "";
      /**
       * <code>optional string instance = 5;</code>
       */
      public java.lang.String getInstance() {
        java.lang.Object ref = instance_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          instance_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string instance = 5;</code>
       */
      public com.google.protobuf.ByteString
          getInstanceBytes() {
        java.lang.Object ref = instance_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instance_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string instance = 5;</code>
       */
      public Builder setInstance(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        instance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string instance = 5;</code>
       */
      public Builder clearInstance() {
        
        instance_ = getDefaultInstance().getInstance();
        onChanged();
        return this;
      }
      /**
       * <code>optional string instance = 5;</code>
       */
      public Builder setInstanceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        instance_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>optional string method = 6;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string method = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string method = 6;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 6;</code>
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 6;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> payload_ = java.util.Collections.emptyList();
      private void ensurePayloadIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          payload_ = new java.util.ArrayList<com.google.protobuf.ByteString>(payload_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated bytes payload = 7;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getPayloadList() {
        return java.util.Collections.unmodifiableList(payload_);
      }
      /**
       * <code>repeated bytes payload = 7;</code>
       */
      public int getPayloadCount() {
        return payload_.size();
      }
      /**
       * <code>repeated bytes payload = 7;</code>
       */
      public com.google.protobuf.ByteString getPayload(int index) {
        return payload_.get(index);
      }
      /**
       * <code>repeated bytes payload = 7;</code>
       */
      public Builder setPayload(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
        payload_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes payload = 7;</code>
       */
      public Builder addPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
        payload_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes payload = 7;</code>
       */
      public Builder addAllPayload(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensurePayloadIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, payload_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes payload = 7;</code>
       */
      public Builder clearPayload() {
        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:HarborMessage)
    }

    // @@protoc_insertion_point(class_scope:HarborMessage)
    private static final com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage();
    }

    public static com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HarborMessage>
        PARSER = new com.google.protobuf.AbstractParser<HarborMessage>() {
      public HarborMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HarborMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HarborMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HarborMessage> getParserForType() {
      return PARSER;
    }

    public com.gg.core.harbor.protocol.HarborOuterClass.HarborMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HandshakeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HandshakeMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HarborMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HarborMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Harbor.proto\"3\n\007Service\022\014\n\004name\030\001 \001(\t\022" +
      "\014\n\004host\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\",\n\020Handshake" +
      "Message\022\030\n\006source\030\001 \001(\0132\010.Service\"\222\001\n\rHa" +
      "rborMessage\022\032\n\004type\030\001 \001(\0162\014.MessageType\022" +
      "\013\n\003sid\030\002 \001(\005\022\013\n\003rid\030\003 \001(\005\022\030\n\006source\030\004 \001(" +
      "\0132\010.Service\022\020\n\010instance\030\005 \001(\t\022\016\n\006method\030" +
      "\006 \001(\t\022\017\n\007payload\030\007 \003(\014*A\n\013MessageType\022\r\n" +
      "\tHandshake\020\000\022\013\n\007Request\020\001\022\014\n\010Response\020\002\022" +
      "\010\n\004Post\020\00324\n\006Harbor\022*\n\004post\022\016.HarborMess" +
      "age\032\016.HarborMessage(\0010\001B\035\n\033com.gg.core.h",
      "arbor.protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Service_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Service_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service_descriptor,
        new java.lang.String[] { "Name", "Host", "Port", });
    internal_static_HandshakeMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HandshakeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HandshakeMessage_descriptor,
        new java.lang.String[] { "Source", });
    internal_static_HarborMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HarborMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HarborMessage_descriptor,
        new java.lang.String[] { "Type", "Sid", "Rid", "Source", "Instance", "Method", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
