// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.gg.example.test.protocol;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code TestRequest}
   */
  public  static final class TestRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TestRequest)
      TestRequestOrBuilder {
    // Use TestRequest.newBuilder() to construct.
    private TestRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TestRequest() {
      id_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TestRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gg.example.test.protocol.Example.internal_static_TestRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gg.example.test.protocol.Example.internal_static_TestRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gg.example.test.protocol.Example.TestRequest.class, com.gg.example.test.protocol.Example.TestRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.gg.example.test.protocol.Example.TestRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.example.test.protocol.Example.TestRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.example.test.protocol.Example.TestRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.example.test.protocol.Example.TestRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.example.test.protocol.Example.TestRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gg.example.test.protocol.Example.TestRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gg.example.test.protocol.Example.TestRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gg.example.test.protocol.Example.TestRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gg.example.test.protocol.Example.TestRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gg.example.test.protocol.Example.TestRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gg.example.test.protocol.Example.TestRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestRequest)
        com.gg.example.test.protocol.Example.TestRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gg.example.test.protocol.Example.internal_static_TestRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gg.example.test.protocol.Example.internal_static_TestRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gg.example.test.protocol.Example.TestRequest.class, com.gg.example.test.protocol.Example.TestRequest.Builder.class);
      }

      // Construct using com.gg.example.test.protocol.Example.TestRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gg.example.test.protocol.Example.internal_static_TestRequest_descriptor;
      }

      public com.gg.example.test.protocol.Example.TestRequest getDefaultInstanceForType() {
        return com.gg.example.test.protocol.Example.TestRequest.getDefaultInstance();
      }

      public com.gg.example.test.protocol.Example.TestRequest build() {
        com.gg.example.test.protocol.Example.TestRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gg.example.test.protocol.Example.TestRequest buildPartial() {
        com.gg.example.test.protocol.Example.TestRequest result = new com.gg.example.test.protocol.Example.TestRequest(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gg.example.test.protocol.Example.TestRequest) {
          return mergeFrom((com.gg.example.test.protocol.Example.TestRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gg.example.test.protocol.Example.TestRequest other) {
        if (other == com.gg.example.test.protocol.Example.TestRequest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gg.example.test.protocol.Example.TestRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gg.example.test.protocol.Example.TestRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TestRequest)
    }

    // @@protoc_insertion_point(class_scope:TestRequest)
    private static final com.gg.example.test.protocol.Example.TestRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gg.example.test.protocol.Example.TestRequest();
    }

    public static com.gg.example.test.protocol.Example.TestRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestRequest>
        PARSER = new com.google.protobuf.AbstractParser<TestRequest>() {
      public TestRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TestRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<TestRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestRequest> getParserForType() {
      return PARSER;
    }

    public com.gg.example.test.protocol.Example.TestRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TestEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 id = 2;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code TestEntry}
   */
  public  static final class TestEntry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TestEntry)
      TestEntryOrBuilder {
    // Use TestEntry.newBuilder() to construct.
    private TestEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TestEntry() {
      name_ = "";
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TestEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gg.example.test.protocol.Example.internal_static_TestEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gg.example.test.protocol.Example.internal_static_TestEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gg.example.test.protocol.Example.TestEntry.class, com.gg.example.test.protocol.Example.TestEntry.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.gg.example.test.protocol.Example.TestEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.example.test.protocol.Example.TestEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.example.test.protocol.Example.TestEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.example.test.protocol.Example.TestEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.example.test.protocol.Example.TestEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gg.example.test.protocol.Example.TestEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gg.example.test.protocol.Example.TestEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gg.example.test.protocol.Example.TestEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gg.example.test.protocol.Example.TestEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gg.example.test.protocol.Example.TestEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gg.example.test.protocol.Example.TestEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestEntry)
        com.gg.example.test.protocol.Example.TestEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gg.example.test.protocol.Example.internal_static_TestEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gg.example.test.protocol.Example.internal_static_TestEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gg.example.test.protocol.Example.TestEntry.class, com.gg.example.test.protocol.Example.TestEntry.Builder.class);
      }

      // Construct using com.gg.example.test.protocol.Example.TestEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        id_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gg.example.test.protocol.Example.internal_static_TestEntry_descriptor;
      }

      public com.gg.example.test.protocol.Example.TestEntry getDefaultInstanceForType() {
        return com.gg.example.test.protocol.Example.TestEntry.getDefaultInstance();
      }

      public com.gg.example.test.protocol.Example.TestEntry build() {
        com.gg.example.test.protocol.Example.TestEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gg.example.test.protocol.Example.TestEntry buildPartial() {
        com.gg.example.test.protocol.Example.TestEntry result = new com.gg.example.test.protocol.Example.TestEntry(this);
        result.name_ = name_;
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gg.example.test.protocol.Example.TestEntry) {
          return mergeFrom((com.gg.example.test.protocol.Example.TestEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gg.example.test.protocol.Example.TestEntry other) {
        if (other == com.gg.example.test.protocol.Example.TestEntry.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gg.example.test.protocol.Example.TestEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gg.example.test.protocol.Example.TestEntry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TestEntry)
    }

    // @@protoc_insertion_point(class_scope:TestEntry)
    private static final com.gg.example.test.protocol.Example.TestEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gg.example.test.protocol.Example.TestEntry();
    }

    public static com.gg.example.test.protocol.Example.TestEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestEntry>
        PARSER = new com.google.protobuf.AbstractParser<TestEntry>() {
      public TestEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TestEntry(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<TestEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestEntry> getParserForType() {
      return PARSER;
    }

    public com.gg.example.test.protocol.Example.TestEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TestResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .TestEntry names = 1;</code>
     */
    java.util.List<com.gg.example.test.protocol.Example.TestEntry> 
        getNamesList();
    /**
     * <code>repeated .TestEntry names = 1;</code>
     */
    com.gg.example.test.protocol.Example.TestEntry getNames(int index);
    /**
     * <code>repeated .TestEntry names = 1;</code>
     */
    int getNamesCount();
    /**
     * <code>repeated .TestEntry names = 1;</code>
     */
    java.util.List<? extends com.gg.example.test.protocol.Example.TestEntryOrBuilder> 
        getNamesOrBuilderList();
    /**
     * <code>repeated .TestEntry names = 1;</code>
     */
    com.gg.example.test.protocol.Example.TestEntryOrBuilder getNamesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TestResponse}
   */
  public  static final class TestResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TestResponse)
      TestResponseOrBuilder {
    // Use TestResponse.newBuilder() to construct.
    private TestResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TestResponse() {
      names_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TestResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                names_ = new java.util.ArrayList<com.gg.example.test.protocol.Example.TestEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              names_.add(input.readMessage(com.gg.example.test.protocol.Example.TestEntry.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          names_ = java.util.Collections.unmodifiableList(names_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gg.example.test.protocol.Example.internal_static_TestResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gg.example.test.protocol.Example.internal_static_TestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gg.example.test.protocol.Example.TestResponse.class, com.gg.example.test.protocol.Example.TestResponse.Builder.class);
    }

    public static final int NAMES_FIELD_NUMBER = 1;
    private java.util.List<com.gg.example.test.protocol.Example.TestEntry> names_;
    /**
     * <code>repeated .TestEntry names = 1;</code>
     */
    public java.util.List<com.gg.example.test.protocol.Example.TestEntry> getNamesList() {
      return names_;
    }
    /**
     * <code>repeated .TestEntry names = 1;</code>
     */
    public java.util.List<? extends com.gg.example.test.protocol.Example.TestEntryOrBuilder> 
        getNamesOrBuilderList() {
      return names_;
    }
    /**
     * <code>repeated .TestEntry names = 1;</code>
     */
    public int getNamesCount() {
      return names_.size();
    }
    /**
     * <code>repeated .TestEntry names = 1;</code>
     */
    public com.gg.example.test.protocol.Example.TestEntry getNames(int index) {
      return names_.get(index);
    }
    /**
     * <code>repeated .TestEntry names = 1;</code>
     */
    public com.gg.example.test.protocol.Example.TestEntryOrBuilder getNamesOrBuilder(
        int index) {
      return names_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < names_.size(); i++) {
        output.writeMessage(1, names_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < names_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, names_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.gg.example.test.protocol.Example.TestResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.example.test.protocol.Example.TestResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.example.test.protocol.Example.TestResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gg.example.test.protocol.Example.TestResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gg.example.test.protocol.Example.TestResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gg.example.test.protocol.Example.TestResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gg.example.test.protocol.Example.TestResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gg.example.test.protocol.Example.TestResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gg.example.test.protocol.Example.TestResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gg.example.test.protocol.Example.TestResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gg.example.test.protocol.Example.TestResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestResponse)
        com.gg.example.test.protocol.Example.TestResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gg.example.test.protocol.Example.internal_static_TestResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gg.example.test.protocol.Example.internal_static_TestResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gg.example.test.protocol.Example.TestResponse.class, com.gg.example.test.protocol.Example.TestResponse.Builder.class);
      }

      // Construct using com.gg.example.test.protocol.Example.TestResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNamesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (namesBuilder_ == null) {
          names_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          namesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gg.example.test.protocol.Example.internal_static_TestResponse_descriptor;
      }

      public com.gg.example.test.protocol.Example.TestResponse getDefaultInstanceForType() {
        return com.gg.example.test.protocol.Example.TestResponse.getDefaultInstance();
      }

      public com.gg.example.test.protocol.Example.TestResponse build() {
        com.gg.example.test.protocol.Example.TestResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gg.example.test.protocol.Example.TestResponse buildPartial() {
        com.gg.example.test.protocol.Example.TestResponse result = new com.gg.example.test.protocol.Example.TestResponse(this);
        int from_bitField0_ = bitField0_;
        if (namesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            names_ = java.util.Collections.unmodifiableList(names_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.names_ = names_;
        } else {
          result.names_ = namesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gg.example.test.protocol.Example.TestResponse) {
          return mergeFrom((com.gg.example.test.protocol.Example.TestResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gg.example.test.protocol.Example.TestResponse other) {
        if (other == com.gg.example.test.protocol.Example.TestResponse.getDefaultInstance()) return this;
        if (namesBuilder_ == null) {
          if (!other.names_.isEmpty()) {
            if (names_.isEmpty()) {
              names_ = other.names_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNamesIsMutable();
              names_.addAll(other.names_);
            }
            onChanged();
          }
        } else {
          if (!other.names_.isEmpty()) {
            if (namesBuilder_.isEmpty()) {
              namesBuilder_.dispose();
              namesBuilder_ = null;
              names_ = other.names_;
              bitField0_ = (bitField0_ & ~0x00000001);
              namesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNamesFieldBuilder() : null;
            } else {
              namesBuilder_.addAllMessages(other.names_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gg.example.test.protocol.Example.TestResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gg.example.test.protocol.Example.TestResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.gg.example.test.protocol.Example.TestEntry> names_ =
        java.util.Collections.emptyList();
      private void ensureNamesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          names_ = new java.util.ArrayList<com.gg.example.test.protocol.Example.TestEntry>(names_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.gg.example.test.protocol.Example.TestEntry, com.gg.example.test.protocol.Example.TestEntry.Builder, com.gg.example.test.protocol.Example.TestEntryOrBuilder> namesBuilder_;

      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public java.util.List<com.gg.example.test.protocol.Example.TestEntry> getNamesList() {
        if (namesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(names_);
        } else {
          return namesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public int getNamesCount() {
        if (namesBuilder_ == null) {
          return names_.size();
        } else {
          return namesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public com.gg.example.test.protocol.Example.TestEntry getNames(int index) {
        if (namesBuilder_ == null) {
          return names_.get(index);
        } else {
          return namesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public Builder setNames(
          int index, com.gg.example.test.protocol.Example.TestEntry value) {
        if (namesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNamesIsMutable();
          names_.set(index, value);
          onChanged();
        } else {
          namesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public Builder setNames(
          int index, com.gg.example.test.protocol.Example.TestEntry.Builder builderForValue) {
        if (namesBuilder_ == null) {
          ensureNamesIsMutable();
          names_.set(index, builderForValue.build());
          onChanged();
        } else {
          namesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public Builder addNames(com.gg.example.test.protocol.Example.TestEntry value) {
        if (namesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNamesIsMutable();
          names_.add(value);
          onChanged();
        } else {
          namesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public Builder addNames(
          int index, com.gg.example.test.protocol.Example.TestEntry value) {
        if (namesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNamesIsMutable();
          names_.add(index, value);
          onChanged();
        } else {
          namesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public Builder addNames(
          com.gg.example.test.protocol.Example.TestEntry.Builder builderForValue) {
        if (namesBuilder_ == null) {
          ensureNamesIsMutable();
          names_.add(builderForValue.build());
          onChanged();
        } else {
          namesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public Builder addNames(
          int index, com.gg.example.test.protocol.Example.TestEntry.Builder builderForValue) {
        if (namesBuilder_ == null) {
          ensureNamesIsMutable();
          names_.add(index, builderForValue.build());
          onChanged();
        } else {
          namesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public Builder addAllNames(
          java.lang.Iterable<? extends com.gg.example.test.protocol.Example.TestEntry> values) {
        if (namesBuilder_ == null) {
          ensureNamesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, names_);
          onChanged();
        } else {
          namesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public Builder clearNames() {
        if (namesBuilder_ == null) {
          names_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          namesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public Builder removeNames(int index) {
        if (namesBuilder_ == null) {
          ensureNamesIsMutable();
          names_.remove(index);
          onChanged();
        } else {
          namesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public com.gg.example.test.protocol.Example.TestEntry.Builder getNamesBuilder(
          int index) {
        return getNamesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public com.gg.example.test.protocol.Example.TestEntryOrBuilder getNamesOrBuilder(
          int index) {
        if (namesBuilder_ == null) {
          return names_.get(index);  } else {
          return namesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public java.util.List<? extends com.gg.example.test.protocol.Example.TestEntryOrBuilder> 
           getNamesOrBuilderList() {
        if (namesBuilder_ != null) {
          return namesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(names_);
        }
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public com.gg.example.test.protocol.Example.TestEntry.Builder addNamesBuilder() {
        return getNamesFieldBuilder().addBuilder(
            com.gg.example.test.protocol.Example.TestEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public com.gg.example.test.protocol.Example.TestEntry.Builder addNamesBuilder(
          int index) {
        return getNamesFieldBuilder().addBuilder(
            index, com.gg.example.test.protocol.Example.TestEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .TestEntry names = 1;</code>
       */
      public java.util.List<com.gg.example.test.protocol.Example.TestEntry.Builder> 
           getNamesBuilderList() {
        return getNamesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.gg.example.test.protocol.Example.TestEntry, com.gg.example.test.protocol.Example.TestEntry.Builder, com.gg.example.test.protocol.Example.TestEntryOrBuilder> 
          getNamesFieldBuilder() {
        if (namesBuilder_ == null) {
          namesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.gg.example.test.protocol.Example.TestEntry, com.gg.example.test.protocol.Example.TestEntry.Builder, com.gg.example.test.protocol.Example.TestEntryOrBuilder>(
                  names_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          names_ = null;
        }
        return namesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TestResponse)
    }

    // @@protoc_insertion_point(class_scope:TestResponse)
    private static final com.gg.example.test.protocol.Example.TestResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gg.example.test.protocol.Example.TestResponse();
    }

    public static com.gg.example.test.protocol.Example.TestResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestResponse>
        PARSER = new com.google.protobuf.AbstractParser<TestResponse>() {
      public TestResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TestResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<TestResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestResponse> getParserForType() {
      return PARSER;
    }

    public com.gg.example.test.protocol.Example.TestResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TestRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TestRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TestEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TestEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TestResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\"\031\n\013TestRequest\022\n\n\002id\030\001 \001" +
      "(\t\"%\n\tTestEntry\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(" +
      "\005\")\n\014TestResponse\022\031\n\005names\030\001 \003(\0132\n.TestE" +
      "ntry2/\n\004Test\022\'\n\004post\022\014.TestRequest\032\r.Tes" +
      "tResponse(\0010\001B\036\n\034com.gg.example.test.pro" +
      "tocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TestRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TestRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_TestEntry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TestEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TestEntry_descriptor,
        new java.lang.String[] { "Name", "Id", });
    internal_static_TestResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TestResponse_descriptor,
        new java.lang.String[] { "Names", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
